// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJes8LMUoBbzj6ZyhqcfuvZadEydTYwF4',
    appId: '1:322101624265:web:dc4cca81ff3b1511817c18',
    messagingSenderId: '322101624265',
    projectId: 'social-media-app-ef3ff',
    authDomain: 'social-media-app-ef3ff.firebaseapp.com',
    storageBucket: 'social-media-app-ef3ff.appspot.com',
    measurementId: 'G-79N433HHEM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF2VZhESaryKvb71Tegy5YiYRsFLCJNzk',
    appId: '1:322101624265:android:98514422cb3bc160817c18',
    messagingSenderId: '322101624265',
    projectId: 'social-media-app-ef3ff',
    storageBucket: 'social-media-app-ef3ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiQeFyvrgVU2qpGMozEnF9D9Jv6y3qTQU',
    appId: '1:322101624265:ios:887fbfa1b0e54c0a817c18',
    messagingSenderId: '322101624265',
    projectId: 'social-media-app-ef3ff',
    storageBucket: 'social-media-app-ef3ff.appspot.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiQeFyvrgVU2qpGMozEnF9D9Jv6y3qTQU',
    appId: '1:322101624265:ios:3998a2114c46b25d817c18',
    messagingSenderId: '322101624265',
    projectId: 'social-media-app-ef3ff',
    storageBucket: 'social-media-app-ef3ff.appspot.com',
    iosBundleId: 'com.example.socialMediaApp.RunnerTests',
  );
}
